### ISSUE TITLE
Make Tags optional to submit blog

### ISSUE THREAD

**Issue by rrolon47** [LaunchCodeLiftoffProjects/Collab-Blog#64]
**Is your feature request related to a problem? Please describe.**
Currently, the tags are required to submit a blog post (if no tags are submitted the blog will not be submitted at all!) Also, there is no validation on tags but there shouldn't be because tags should be optional and flexible like a hashtag. 

**Describe the solution you'd like**
Tags should be made optional, if you dont select or add any tags you should still be able to submit them.  A possible option would be to see if it is null or undefined and if so submit a null response to the database.  

**Describe alternatives you've considered**
If there is something that is restricting you from submitting without tags that should be removed. 

**Additional context**
In the meeting on 4/28/22 we discussed how we would like tags to function deciding that they should be optional thus validation is not required for it.

**Comment by rrolon47** [comment]
@baubsy Hey Robert,  Since you completed the tags issue back in November we were hoping you could attend a future meeting to go through the code you wrote for tags and explain what could be preventing us from submitting a blog with no tags and how to make tags an optional input.

**Comment by baubsy** [comment]
@rrolon47 I took a look at this today. It is submitting the blog still but it's causing the backend to throw an error before it saves the blog and sends the response back. I think I incorrectly set the initial value of tags in reactiveForm. Right now it's set to an empty string and if no tags are added it stays an empty string. When it hits the backend it throws an error because it can't turn an empty string into an array for the Blog object's Tags array. Setting the initial value of tags to an empty array seems to fix the issue. I'll submit a pull request once I've tested it a bit more and I'll try to be at the next meeting in case anyone wants to talk about it.
